language: php

dist: trusty

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

matrix:
  allow_failures:
    - php: 7.4snapshot
  include:
    - php: 5.3
      dist: precise

sudo: false

install:
  - composer install
  - ./vendor/bin/simple-phpunit install

script: ./vendor/bin/simple-phpunit -v --coverage-text --coverage-clover=coverage.clover

after_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi'
